---
- name: check
  command: which java
  ignore_errors: True
  register: check_java

- name: download npm
  shell: |
    cd {{srcdir}}
    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
  when: check_java|failed

- name: install jdk 8
  yum: name={{srcdir}}/jdk-8u131-linux-x64.rpm
  when: check_java|failed
