---
- name: check if exist apache src file (when failed, not downloaded)
  command: service httpd status
  ignore_errors: True
  register: check_apache

- name: get apache source file  # ソースファイルをダウンロードする
  command: chdir={{srcdir}} wget http://ftp.kddilabs.jp/infosystems/apache/httpd/{{apache2}}.tar.gz
  when: check_apache|failed

- name: tar apache
  command: chdir={{srcdir}} tar xvf {{apache2}}.tar.gz
  when: check_apache|failed

- name: configure apache
  command: chdir={{srcdir}}/{{apache2}} ./configure
  when: check_apache|failed

- name: make apache
  command: chdir={{srcdir}}/{{apache2}} make
  when: check_apache|failed

- name: install apache
  command: chdir={{srcdir}}/{{apache2}} make install
  when: check_apache|failed
