---
- name: for puppet CentOS https://docs.puppet.com/puppet/latest/puppet_platform.html
  command: rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
  ignore_errors: True # 2回目以降はエラーが出ることがあるので ignore erros
