- hosts: all  # とりあえず all
  sudo: true
  user: vagrant
  vars:
    emacs: emacs-24.5  # http://ftp.jaist.ac.jp/pub/GNU/emacs/emacs-24.5.tar.gz
    srcdir: /usr/local/src  # tar.gz をダウンロードして展開するディレクトリ
  roles:
    - puppetrpm
    - yum
    - gccmake
    - git
    - openssl
    - emacs
    - zsh
    - php70
    - php56
    - mysql57
    - java8
    - scala